# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarLog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarLog

  pod 'inavi-maps-sdk'

  pod 'EasyTipView', '~> 2.1'

end
